Update CI and Tests
Update CI to publish coverage reports and update method for reporting
tests results. Add test case for basic command example.

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -54,15 +54,21 @@ jobs:
       - name: Install Packages
         run: npm i
 
-      - name: Test
-        run: npm test -- --ci --reporters=default --reporters=jest-junit
+      - name: Run Tests with Coverage Report
+        run: npm run coverage
 
       - name: Report Test Results
-        uses: IgnusG/jest-report-action@v2.3.3
-        if: always()
+        uses: dorny/test-reporter@v1.6
+        if: success() || failure()        # run this step even if previous step failed
         with:
-          access-token: ${{ secrets.GITHUB_TOKEN }}
-          junit-file: junit.xml
+          name: JEST Tests                # Name of the check run which will be created
+          path: ./reports/jest-junit.       # Path to test results
+          reporter: jest-junit            # Format of test results
+
+      - name: Report Coverage
+        uses: romeovs/lcov-reporter-action@v0.2.16
+        with:
+          lcov-file: ./coverage/lcov.info
 
   build:
     needs: test
